---
- name: join worker machine
  command: "{{ kubernetes_join_command }}" # shell is required; ansible-lint 305.
  args:
    creates: /etc/kubernetes/kubelet.conf
  when: kubernetes_join_command is defined
# The 'creates' arg does not accept a list; these file(s) are what kubeadm is  checking for
#    - /etc/kubernetes/kubelet.conf
#    - /etc/kubernetes/pki/ca.crt
